### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by DCbryant** [Haixiang6123/one-day-one-npm-lib#1]
可以写一下是怎么分析出这些原理的吗？是直接看源码吗？授人以鱼也可以授人以渔😂

**Comment by haixiangyan** [comment]
我是直接看源码去推演的，但是整个推演的过程还是比较痛苦的：

1. 先看看懂源码，整理源码的链路，细节可以不管，比如类型判断，参数合法性这些
2. 源码看完，思考这个库要解决的根本问题是什么，比如 redux 解决的就是事件总线的问题
3. 找到要解决的根本问题之后，就设想一个最简单的需求，然后写一个最Low的版本出来，比如最 Low 的 redux 就是做一个事件总线出来
4. 一步步将细节完善成源码的样子，比如上面的加上中间件、洋葱模型、observable 等

个人觉得第一步其实也挺难的，好在网上有很多分析源码的博客可以帮你理清思路和链路。但是第四步真的只能靠自己的思考了，因为很少人会从根本问题去做推导，这一步的技巧就是不断问为什么：为什么这么设计？为什么那样不行？所以最后一步也是最难的。

希望对你有帮助😄

**Comment by DCbryant** [comment]
> 我是直接看源码去推演的，但是整个推演的过程还是比较痛苦的：
> 
> 1. 先看看懂源码，整理源码的链路，细节可以不管，比如类型判断，参数合法性这些
> 2. 源码看完，思考这个库要解决的根本问题是什么，比如 redux 解决的就是事件总线的问题
> 3. 找到要解决的根本问题之后，就设想一个最简单的需求，然后写一个最Low的版本出来，比如最 Low 的 redux 就是做一个事件总线出来
> 4. 一步步将细节完善成源码的样子，比如上面的加上中间件、洋葱模型、observable 等
> 
> 个人觉得第一步其实也挺难的，好在网上有很多分析源码的博客可以帮你理清思路和链路。但是第四步真的只能靠自己的思考了，因为很少人会从根本问题去做推导，这一步的技巧就是不断问为什么：为什么这么设计？为什么那样不行？所以最后一步也是最难的。
> 
> 希望对你有帮助😄

**Comment by DCbryant** [comment]
> 我是直接看源码去推演的，但是整个推演的过程还是比较痛苦的：
> 
> 1. 先看看懂源码，整理源码的链路，细节可以不管，比如类型判断，参数合法性这些
> 2. 源码看完，思考这个库要解决的根本问题是什么，比如 redux 解决的就是事件总线的问题
> 3. 找到要解决的根本问题之后，就设想一个最简单的需求，然后写一个最Low的版本出来，比如最 Low 的 redux 就是做一个事件总线出来
> 4. 一步步将细节完善成源码的样子，比如上面的加上中间件、洋葱模型、observable 等
> 
> 个人觉得第一步其实也挺难的，好在网上有很多分析源码的博客可以帮你理清思路和链路。但是第四步真的只能靠自己的思考了，因为很少人会从根本问题去做推导，这一步的技巧就是不断问为什么：为什么这么设计？为什么那样不行？所以最后一步也是最难的。
> 
> 希望对你有帮助😄

谢谢大佬，很有帮助
