### ISSUE TITLE
仓库网站链接似乎挂了

### ISSUE THREAD

**Issue by Volcano-Yang** [Haixiang6123/one-day-one-npm-lib#2]
<img width="697"  src="https://user-images.githubusercontent.com/43328103/150454749-d88f6de1-7414-475d-9c32-a95c4da852c5.png">

![image](https://user-images.githubusercontent.com/43328103/150454793-353f61c4-e571-4866-9ed0-3bd0d4748553.png)

**Comment by haixiangyan** [comment]
fixed，感谢！其实里面就是个目录😅
